name: CI Monorepo

on:
 push:
  branches: [develop, master]
 pull_request:
  branches: [develop, master]

jobs:
 test-client:
  name: Test Client
  runs-on: ubuntu-latest
  defaults:
   run:
    working-directory: ./client

  steps:
   - name: Checkout repository
     uses: actions/checkout@v3

   - name: Setup Node.js
     uses: actions/setup-node@v3
     with:
      node-version: 18

   - name: Install dependencies
     run: npm install

   - name: Run client tests
     run: npm test

 test-server:
  name: Test Server
  runs-on: ubuntu-latest
  defaults:
   run:
    working-directory: ./server

  steps:
   - name: Checkout repository
     uses: actions/checkout@v3

   - name: Setup Node.js
     uses: actions/setup-node@v3
     with:
      node-version: 18

   - name: Install dependencies
     run: npm install

   - name: Run server tests
     run: npm test
